// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://khffmkbqvcppybpdrusi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtoZmZta2JxdmNwcHlicGRydXNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzNDI3ODUsImV4cCI6MjA2NzkxODc4NX0.o4UWa-3ANjYBIsQjGcq9BUuaytSpSwBdraLTvpM6Pps";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});